- .github/workflows/build-containers.yml
- opensciencegrid/frontier-squid/Dockerfile
- opensciencegrid/oidc-agent/Dockerfile
- opensciencegrid/ospool-cm/Dockerfile
> Actually build images based on the specified release series

- .github/workflows/build-containers.yml
Direct pushes are failing so I'm submitting this PR
> Fix missing line continuations

- opensciencegrid/vo-frontend/patches/3.9.6.sh
See https://github.com/glideinWMS/glideinwms/issues/242
> GWMS frontend patch to fix factory monitoring

- opensciencegrid/mailchimp-sync/Dockerfile
- opensciencegrid/mailchimp-sync/README.md
- opensciencegrid/mailchimp-sync/mailchimp-sync/.gitignore
- opensciencegrid/mailchimp-sync/mailchimp-sync/runme.sh
- opensciencegrid/mailchimp-sync/mailchimp-sync/sync.py
mailchimp-sync: keep MailChimp up to date with membership information from Connect and Comanage. This will run as a k8s cronjob.
> OSPOOL-47: Image for MailChimp syncing

- opensciencegrid/sssd/Dockerfile
- opensciencegrid/sssd/etc/osg/image-init.d/sssd-init.sh
- opensciencegrid/sssd/etc/supervisord.d/sssd.conf
Pick a higher UID/GID to avoid collisions such as https://github.com/opensciencegrid/docker-xcache/pull/97#issuecomment-1416493767
> Add an SSSD image (SOFTWARE-5464)

- opensciencegrid/gwms-factory/Dockerfile
- opensciencegrid/gwms-factory/README.md
- opensciencegrid/gwms-factory/etc/gwms-factory/hooks.reconfig.pre/hostedce_gen
- opensciencegrid/gwms-factory/etc/osg/image-init.d/05_copy_condor_configs.sh
- opensciencegrid/gwms-factory/etc/osg/image-init.d/05_download_tarballs.sh
- opensciencegrid/gwms-factory/etc/osg/image-init.d/10_change_own.sh
- opensciencegrid/gwms-factory/etc/osg/image-init.d/15_clone.sh
- opensciencegrid/gwms-factory/etc/osg/image-init.d/20_link_configs.sh
- opensciencegrid/gwms-factory/etc/osg/image-init.d/30_gwms_upgrade.sh
- opensciencegrid/gwms-factory/etc/osg/image-init.d/40_gwms_reconfig.sh
- opensciencegrid/gwms-factory/etc/supervisord.d/10_gwms_factory.conf
> Add gwms-factory image

- opensciencegrid/ospool-ganglia/90-ospool-php.ini
- opensciencegrid/ospool-ganglia/Dockerfile
- opensciencegrid/ospool-ganglia/ganglia-web-overrides/conf.php
- opensciencegrid/ospool-ganglia/ganglia.d/50-ospool
- Change default tz to America/Chicago
- Added tracking of RecentJobsExitException
> OSPool: minor adjustments to Ganglia display

- opensciencegrid/gwms-factory/etc/osg/image-init.d/20_link_configs.sh
- Create config.d directory
- Exit on error
- Add quotes in the unlikely event we've got embedded spaces
> gwms-factory: Update config.d symlink script

- opensciencegrid/frontier-squid/README.md
> Use recommended image tag for frontier-squid

- opensciencegrid/gwms-factory/etc/gwms-factory/hooks.reconfig.pre/hostedce_gen
- opensciencegrid/gwms-factory/etc/osg/image-init.d/15_clone.sh
- Ensure git repos cloned on startup are owned by gfactory
- Remove interactive prompt from hostedce_gen, correcting bash error introduced previously
> gwms-gfactory: Image startup fixes

- opensciencegrid/frontier-squid/start-frontier-squid.sh
I forgot to include this in #111.
> Include /etc/sysconfig/frontier-squid when starting frontier-squid unprivileged

- opensciencegrid/frontier-squid/10-chown-mount-points.sh
Only chown mounted squid dirs if they have incorrect permissions at the top level
> SOFTWARE-5245: frontier-squid - check existing permissions first

- .github/CODEOWNERS
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
> Try out CODEOWNERS file on a handful of images

- opensciencegrid/gwms-factory/Dockerfile
- opensciencegrid/gwms-factory/etc/osg/image-init.d/10_change_own.sh
- opensciencegrid/gwms-factory/var/lib/gwms-factory/web-base/singularity_lib.sh
This adds missing directory creation in factory bootstrapping, and overrides the singularity_lib.sh to include a fix that was never released in gwms
> Fact 230901

- .github/workflows/build-containers.yml
- opensciencegrid/cvmfs-nodeplugin/Dockerfile
- opensciencegrid/gracc-apel/Dockerfile
- opensciencegrid/gwms-factory/Dockerfile
- opensciencegrid/oidc-agent/Dockerfile
- opensciencegrid/ospool-display/Dockerfile
- opensciencegrid/sssd/Dockerfile
- opensciencegrid/vo-frontend/Dockerfile
- opensciencegrid/xrootd-standalone/Dockerfile
I left all the images that directly referenced EL8 as is since I didn't want to force them back to EL7 for OSG 3.6 images
> Add OSG 23 images (SOFTWARE-5673)

- .github/workflows/build-containers.yml
- opensciencegrid/central-collector/.github/workflows/build-sw-container.yml
> Fix set-output deprecation warnings (software-5354)

- opensciencegrid/mailchimp-sync/mailchimp-sync/sync.py
> OSPool comanage: moving to ap40 group

- opensciencegrid/gracc-apel/Dockerfile
- opensciencegrid/gracc-apel/apel_report.py
- opensciencegrid/gracc-apel/test_apel_report.py
This is documented here: https://docs.google.com/document/d/19EerfwmzhUM4gLijOK9XxAM46vg1E2oSJvWVoEltvRA/edit
> Adding HEPScore support to the apel reporting

- opensciencegrid/svn-to-git/Dockerfile
In preparation for https://github.com/opensciencegrid/docker-software-base/pull/86#issuecomment-2150205743
> Move to standard EL8 base

- opensciencegrid/access-amie/Dockerfile
- opensciencegrid/osgconnect-report/Dockerfile
Preparing to move access-amie and osgconnect-report to osg23 and el9 in tiger.
> Moving images to OSG23/el9

- opensciencegrid/gracc-apel/Dockerfile
- Upgrade apel-ssm
- Install python3-argo-ams-library from prod repo
- Refactor dockerfile
- Remove fetch-crl
> gracc-apel: Switch to EL9

- opensciencegrid/ospool-cm/opt/ospool/update-prios
> Prio boost for Dan

- opensciencegrid/koji-builder/Dockerfile
The new Koji CA cert will be included in this bundle
> koji-builder: add osg-internal-cas

- opensciencegrid/ospool-cm/prometheus.py
Added blackhole metric to the Prometheus stats collection.
> OSPool CM: Collect stats on blackhole resources

- opensciencegrid/vo-frontend/Dockerfile
> OSPool ITB: GWMS packages shows up first in osg-upcoming-development

- opensciencegrid/cvmfs-nodeplugin/build-config.json
No reason to build six images for this.
> Only build cvmfs-nodeplugin for 24-release
