opensciencegrid/images

- .github/workflows/build-containers.yml
- opensciencegrid/frontier-squid/Dockerfile
- opensciencegrid/oidc-agent/Dockerfile
- opensciencegrid/ospool-cm/Dockerfile
This PR should fix the CI for pushes to personal forks (for both `main` and any other branch) and still work for PRs and pushes to `main` on this fork. Since this includes #2 , it should build all 3 images that we currently have and once that's merged, we can kick off these tests again and all the build jobs will be skipped.
> Fixes to the changed image list generation for pushes/PRs

- opensciencegrid/xrootd-standalone/Dockerfile
- opensciencegrid/xrootd-standalone/image-config.d/10-create-macaroon-secret.sh
Copy of https://github.com/opensciencegrid/docker-xrootd-standalone/pull/20
> Create macaroon at run time, not build time

- opensciencegrid/central-syslog/etc/logrotate.d/remote-messages
(copied from [opensciencegrid/central-syslog #2](https://github.com/opensciencegrid/central-syslog/issues/2)
> Logrotate remote-messages hourly

- opensciencegrid/central-syslog/Dockerfile
Copied from https://github.com/opensciencegrid/central-syslog/commit/ac4eec0ce1745b394ed61ac4d480d52ba223652f
> Run logrotate every hour so it can rotate logs every hour

- .github/workflows/build-containers.yml
Need this before submitting the `ospool-ap` PR so we don't get 90+ repeat image builds
> Avoid duplicate dirs in the image list

- .github/workflows/build-containers.yml
This consolidates a number of jobs so that the GHA UI doesn't barf (though I do have a ticket open with them about it):
- Different release series builds into a single build job but still runs separate `(development, testing, release)` per image. I decided to keep it this way so that we can allow the `development` builds to fail without preventing us from pushing `testing` and `release` images
- All pushes for a given image into a single push job
Test run here: https://github.com/brianhlin/osg-images/actions/runs/2035965206. Spot-checked builds and it looks like they're selecting the appropriate 3.5 vs 3.6 base images in each build. Pushes fail (as expected) because I didn't set up the relevant secrets but they at least look like they're trying to pull down the relevant build caches
> Consolidate per-image jobs (SOFTWARE-5098)

- opensciencegrid/frontier-squid/README.md
Barry recommends 50GB to 100 GB in [GGUS#158468](https://ggus.eu/index.php?mode=ticket_info&ticket_id=158468).
> Add recommended production frontier cache size to container docs (SOFTWARE-5289)

- opensciencegrid/central-collector/Dockerfile
- opensciencegrid/central-collector/etc/osg/image-init.d/50-collector-tokens.sh
If signing keys are present in the container, make a copy of them into the expected location.  This will enable us to make IDTOKENS for the central-collector which are valid between restarts.
> Copy signing keys and fix perms

- opensciencegrid/osdf-collector/Dockerfile
- opensciencegrid/osdf-collector/LICENSE
- opensciencegrid/osdf-collector/README.md
- opensciencegrid/osdf-collector/etc/condor/config.d/50-osdf-collector.conf
- opensciencegrid/osdf-collector/etc/condor/mapfile
- opensciencegrid/osdf-collector/etc/rsyslog.conf
- opensciencegrid/osdf-collector/etc/supervisord.d/htcondor.conf
- opensciencegrid/osdf-collector/etc/supervisord.d/rsyslogd.conf
This is a simple container meant to run a HTCondor collector on behalf of the OSDF.
Collector status information in a container is an old idea; we have about 5 of the OSDF cache installs reporting to collector.opensciencegrid.org currently.  This represents a fresh approach where we'll have a combination of topology and the shovelers pushing ads to the collector, then have a dedicated OSDF webapp doing matchmaking between clients and sites.  The long-term goal is to provide an abstraction layer between OSDF and other OSG services so one could setup a standalone OSDF without any other OSG-provided service (turning OSDF more into a software product).
But for now, just a collector.
(Oh, and a collector with rsyslog integration so the container logs "do the right thing")
> OSDF Collector

- opensciencegrid/mailchimp-sync/mailchimp-sync/sync.py
I'm seeing jobs fail with
```
Traceback (most recent call last):
File "sync.py", line 326, in <module>
main()
File "sync.py", line 290, in main
comanage_find_users(users)
File "sync.py", line 128, in comanage_find_users
if n['PrimaryName'] == True:
KeyError: 'PrimaryName'
```
I'm assuming that `n` is a dict
> Handle values without a PrimaryName

- .github/workflows/build-containers.yml
push-container-action@v0.5.0 expects underscores to separate cache key elements
https://github.com/opensciencegrid/push-container-action/blob/v0.5.0/action.yml#L73
build-container-action@v0.3.0 uses dashes
https://github.com/opensciencegrid/build-container-action/blob/v0.3.0/action.yml#L57
Switch build-container-action to v0.3.1 to use underscores
https://github.com/opensciencegrid/build-container-action/blob/v0.3.1/action.yml#L57
> Update CI to use opensciencegrid/build-container-action@v0.3.1

- .github/workflows/build-containers.yml
Includes fix for extra curly brace from https://github.com/opensciencegrid/build-container-action/commit/7791700dbfd6b7ec17add110d4bd1a66e9cc543f
```
Run actions/cache@v2
with:
path: /tmp/.buildx-cache
key: gwms-factory}_3.6_development_buildx_ebb5f1c8b5dec9b8f427a6c72d07948e0db2fc86_4940437215
Cache not found for input keys: gwms-factory}_3.6_development_buildx_ebb5f1c8b5dec9b8f427a6c72d07948e0db2fc86_4940437215
```
> Update CI to use opensciencegrid/build-container-action@v0.4.1

- opensciencegrid/frontier-squid/Dockerfile
- opensciencegrid/frontier-squid/README.md
- opensciencegrid/frontier-squid/start-frontier-squid.sh
This builds on opensciencegrid/docker-software-base#70 to enable the OSG frontier-squid container to be run from Apptainer or OKD.
> Support running frontier-squid container from unprivileged apptainer or OKD

- opensciencegrid/ospool-cm/10-rotate-logs
- opensciencegrid/ospool-cm/Dockerfile
- opensciencegrid/ospool-cm/ospool-overview/utils/cron-5m.sh
- opensciencegrid/ospool-cm/ospool-overview/utils/cron-hourly.sh
- opensciencegrid/ospool-cm/prometheus.py
- Log rotation to make sure health script does not pick up issues from previous instances
- Adjusted Prometheus thresholds for mem/disk starvation
- Configured overview to only get data from cm-1, for consistency
> OSPool CM: Added log rotation, adjusted config

- opensciencegrid/gwms-factory/Dockerfile
Of the outbound email options, msmtp seems like the best. Both sSMTP and esmtp are no longer maintained.
> gwms-factory: Add msmtp package

- opensciencegrid/frontier-squid/10-chown-mount-points.sh
- opensciencegrid/frontier-squid/Dockerfile
Add init script that chowns mounted squid runtime directories, and exits on failure
> SOFTWARE-5245-frontier-squid-directory-permissions

- opensciencegrid/xrootd-standalone/image-config.d/10-add-users.sh
From the xargs manpage, the command is run once even if there is no input, unless `--no-run-if-empty` is passed.
> Do not run `adduser` if we have no users to add

- opensciencegrid/koji-builder/Dockerfile
Update koji-builder to 1.21.1; don't run separate chmod commands, and mount /var/cache/dnf as a cache to avoid having it be included in a layer
> koji-builder: efficiency and new version

- opensciencegrid/koji-builder/Dockerfile
- opensciencegrid/koji-builder/create-config.sh
- Require KOJID_USER; `hostname -f` is pretty bad, even in a StatefulSet
- Add missing KOJID_CERTKEY
> koji-builder fixups

- opensciencegrid/osgstorage-redirector/Dockerfile
Moving to EL9 would add OpenSSL 3, which needs a bit more care. Moving to EL8 would be a good intermediate step.
> osgstorage-redirector: Move from EL7 to EL8

- .github/workflows/build-containers.yml
This change pulls in this commit https://github.com/opensciencegrid/push-container-action/commit/2e545716e73fff096b749c52c2d507b26e389d27
> Use the latest main for the OSG push container action, fix base_os

- opensciencegrid/gwms-factory/Dockerfile
If the yum command fails, it leads to a confusing pip3 error on EL9
> gwms-factory: Move el7 pyyaml install to its own RUN section

- opensciencegrid/ospool-ganglia/view_chtc-spark.json
Miron requested that on the CE Dashboard graphs, the GlideinsRunning data series should be on the bottom of the stacked graph, instead of GlideinsIdle.
> On CE dashboard, put GlideinRunning data on the bottom.

- opensciencegrid/contact-sync/contact_sync.py
Slack channel and other notifications won't have email entries
> contact-sync: Ignore (un)subscribers without emails

- opensciencegrid/ospool-cm/opt/ospool/update-prios
- opensciencegrid/ospool-cm/prometheus.py
- Added gpus stats to the prometheus probe
- Changed priorities update script to only use the main negotiator and ignore the bring-your-own-resources negotiators
> OSPool: Updated prometheus and prio scripts

- opensciencegrid/s3-backup/Dockerfile
UBI micro does not include dnf
> s3-backup: Modify to use UBI minimal source, rather than inheriting micro

- opensciencegrid/gracc-apel/Dockerfile
- opensciencegrid/gracc-apel/apel_report.py
```
[root@c2dcc9a1d871 ~]# /usr/libexec/apel/apel_report.py
...
File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 638, in raise_error
raise UnsupportedProductError(message)
elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not Elasticsearch and we do not support this unknown product
```
> gracc-apel: Switch python client to opensearch-py

- opensciencegrid/ospool-ganglia/51-ganglia-ce-dashboards.conf
Enable reset metrics functionality in the condor_gangliad, which first appears in HTCSS version 23.6.x.  This functionality is critical to keeping the CE Dashboard data correct. Note the ospool-container container should ideally not be rebooted until it such time as the image will contain HTCSS 23.6.x.
> Update 51-ganglia-ce-dashboards.conf to configure reset metrics

- opensciencegrid/vo-frontend/patches/3.10.6.sh
GWMS currently has a mapfile with:
```
SSL (.*) anonymous
```
Then in the generated config under `/var/lib/gwms-frontend/vofrontend/frontend.condor_config`, they have `DENY_CLIENT = anonymous@*` which means the frontend can not query the AP queues over SSL. This patch adds SSL to the auth methods, and sets `DENY_CLIENT = no-deny` (it has to override the default value).
> vo-frontend: added patch to enable querying of APs via SSL

- opensciencegrid/ospool-cm/healthy.sh
- opensciencegrid/vo-frontend/healthy.sh
These are important to trigger HA failover to the secondary CM, and make sure the frontend resets in case of problems.
> OSPool: include z/d processes in the health checks

- opensciencegrid/vo-frontend/healthy.sh
gwms triggers these with the way they do subprocesses
> Removed zombie/deadlock checks for fe

- opensciencegrid/frontier-squid/start-frontier-squid.sh
A closed issue in supervisord recommends sending a SIGINT to supervisord at the end of a supervised process as a potential approach for exiting on the exit of the service: https://github.com/Supervisor/supervisor/issues/712 Since supervisord is the init process of this container, the whole container will exit if the waited-on squid process ends in `start-frontier-squid.sh`
> SOFTWARE-5448: Exit the supervisord init process if squid exits

- .github/workflows/build-containers.yml
Build 3.6 images in el9 instead of el7
> SOFTWARE-5924: Remove el7 builds from Github Workflows

- opensciencegrid/gwms-factory/etc/osg/image-init.d/16_prep_tarball_script.sh
We used to pull get_tarball.py script from factools. Now it is supplied by gwms, so use that one instead.
> use gwms provided tarball script

- opensciencegrid/ospool-cm/opt/ospool/update-prios
Priority factors will be adjusted based on held job (and in the future, maybe goodput/badput). This will slow down workloads which results in a lot of held jobs.
> Change OSPool prioritiy factors to be based on workload performance

- .github/workflows/build-containers.yml
In https://github.com/opensciencegrid/images/pull/204, we changed the push job matrix from one push job per image name to one push per image name, base OS, base OSG repo combination. This was necessary to support per-image configurations but now the per-repo push job steps are unnecessary as the repo is encoded at the job level now.
> Fix issue with push jobs skipping over Harbor dev

- .github/workflows/build-containers.yml
This change to the push job will allow the push job to determine what repo (development, testing, release) to push to based on the images config string. This ensures that an individual image doesn't get pushed to multiple repos for a single GHA job for that specific image. 
An example config string for an image may be: el9-23-development-True-False
In this case the push job will push to the development repo for both docker and harbor, previously it would have pushed to all three repos development, testing, and release for both docker and harbor.
> Resolved issue with push job to use the image config string to determine what repo to push to for docker and harbor per image

- opensciencegrid/access-amie/build-config.json
- opensciencegrid/central-syslog/build-config.json
- opensciencegrid/contact-sync/build-config.json
- opensciencegrid/default-build-config.json
- opensciencegrid/gracc-apel/build-config.json
- opensciencegrid/koji-builder/build-config.json
- opensciencegrid/logrotate/build-config.json
- opensciencegrid/mailchimp-sync/build-config.json
- opensciencegrid/osgconnect-report/build-config.json
- opensciencegrid/ospool-static-registry/build-config.json
- opensciencegrid/s3-backup/build-config.json
- opensciencegrid/sssd/build-config.json
- opensciencegrid/stompclt/build-config.json
- opensciencegrid/svn-to-git/build-config.json
- scripts/build-job-matrix.py
There's no sense in having OSG development / testing images for images that don't actually pull in any OSG RPMs.
Note that many of these images actually do get some OSG Software from the software-base image but in those cases, they don't pull any subsequent packages, i.e. the image functionality does not depend on the OSG Software RPM replease pipeline. Many of these images mostly want to use the runtime `/etc/osg/image-init.d` feature from the base image.
> Reduce number of builds for images without OSG Software

- opensciencegrid/ospool-cm/healthy.sh
A few uninterruptible can be expected. We don't want to trigger the health probe failure until there are a bunch of them (>3).
> OSPool CM: relax the D proc check

- opensciencegrid/access-amie/build-config.json
- opensciencegrid/central-syslog/build-config.json
- opensciencegrid/contact-sync/build-config.json
- opensciencegrid/default-build-config.json
- opensciencegrid/gracc-apel/build-config.json
- opensciencegrid/koji-builder/build-config.json
- opensciencegrid/logrotate/build-config.json
- opensciencegrid/mailchimp-sync/build-config.json
- opensciencegrid/osgconnect-report/build-config.json
- opensciencegrid/ospool-static-registry/build-config.json
- opensciencegrid/s3-backup/build-config.json
- opensciencegrid/sssd/build-config.json
- opensciencegrid/stompclt/build-config.json
- opensciencegrid/svn-to-git/build-config.json
- Add OSG 24 to build matrices
The GHA for the first (reverted) commit in this PR tests building every image into 24-development, all builds succeed: https://github.com/mwestphall/images/actions/runs/11521078633/job/32073908568
> SOFTWARE-6022: OSG-24

- opensciencegrid/s3-backup/s3-backup.sh
Add the `--dry-run` flag following the suggestion from Matyas in https://github.com/opensciencegrid/images/pull/223#pullrequestreview-2512467507.
> s3-backup: Add optional --dry-run argument, passed through to mc mirror

- opensciencegrid/gracc-apel/Dockerfile
k8s containers have a high nofiles ulimit (1073741816) and this causes python-daemon to use a large amount of RAM, leading to OOM.
This is fixed in v3 of python-daemon. https://pagure.io/python-daemon/issue/72
> gracc-apel: Update python-daemon to address high memory usage

- opensciencegrid/frontier-squid/start-frontier-squid.sh
The /etc/init.d/frontier-squid script was moved to /usr/libexec/squid/frontier-squid in frontier-squid-5.9-3.2+. Try the new path first, and fall back to the old path.
> frontier-squid: Adjust startup script for path change

- opensciencegrid/ospool-ganglia/51-ganglia-ce-dashboards.conf
This is required to talk to collector.opensciencegrid.org, and prolly other central managers, that require authentication and use an InCommon SSL cert.
> Configure to use grid-security to find CA certs.

- opensciencegrid/ospool-cm/healthy.sh
Pods are currently reporting sporadic health check failure due to the zombie limit being low.
> OSPool: Minor adjustment to health zombie process check

- opensciencegrid/gracc-apel/build-config.json
- opensciencegrid/koji-builder/build-config.json
- opensciencegrid/logrotate/build-config.json
- opensciencegrid/ospool-static-registry/build-config.json
- opensciencegrid/s3-backup/build-config.json
- opensciencegrid/svn-to-git/build-config.json
This won't affect running services:
- gracc-apel: using "latest"
- koji-builder: using 24-release already (albeit with a timestamped version)
- logrotate: using 24-release (or a timestamped version of 23-release or 24-release)
- svn-to-git: using either a fixed version or 23-testing (which doesn't get automatically built)
- s3-backup: using an image from 2021
- ospool-static-registry: using 23-development (which doesn't get automatically built)
> Stop building some internal images for OSG 23

- opensciencegrid/koji-builder/Dockerfile
- opensciencegrid/koji-builder/build
- opensciencegrid/koji-builder/create-config.sh
- Set BASE_OSG_SERIES to 24
- Drop support for BASE_OSG_SERIES==3.6
- Add support for building from github.com/osg-htc/software-packaging
> koji-builder: updates

- opensciencegrid/git-safe-backup/Dockerfile
- opensciencegrid/git-safe-backup/ghb.py
- opensciencegrid/git-safe-backup/github-metadata-backup.sh
- opensciencegrid/git-safe-backup/safe-backup.sh
- Combine git and github metadata backup scripts into single docker image
- Remove output to persistent logging directories since logging is now handled via kubernetes
> Add github metadata backup script to git-safe-backup image

- opensciencegrid/vo-frontend/supervisor.d/10-gwms-fe.conf
By default, supervisord doesn't change HOME or other environment vars, and so even if you run a service as a different user, HOME will be /root unless set otherwise. This wasn't a problem until gWMS made a change to make the frontend look at $HOME to set its token dir:
https://github.com/glideinWMS/glideinwms/commit/1d7fa0af05d4d30c303c68c5d8bdc5d296176787
> Explicitly set the HOME dir for the frontend

- opensciencegrid/ospool-cm/opt/ospool/update-prios
1. Only run the prio update script on the primary pod in the HA setup
2. Adjusted Danny's temporary priority
> OSPool prio updates

- opensciencegrid/logrotate/Dockerfile
Since log rotation is based on date or size, this doesn't cause the logs to be rotated more frequently, it just causes logrotate to check for the rotation condition more frequently, allowing it to catch sudden growths in size. logrotate itself has locking so this should be safe.
> Bump the default frequency of the logrotate cron job

- opensciencegrid/ospool-cm/opt/ospool/update-prios
- opensciencegrid/ospool-cm/ospool.cron
No need for the hostname selection and cron call in here anymore
> Moved the prio update to a k8s cronjob

- scripts/build-job-matrix.py
- scripts/detect-changed-images.py
In the case that the GHA is being run without a previous commit, eg. in the case of a non-pull-request dispatch, the GHA will try to run `detect-changes-images.py --before` with no arg to before. This change allows the script to be run when the argument is supplied in that way.
eg: https://github.com/mwestphall/images/actions/runs/16604754099/job/46973554960
Also, output an empty build matrix rather than error-ing when no changed images are detected (such as in the case of this pull request)
> Allow no arguments to the --before flag 
